config/routes.rb
Zend::Application.routes.draw do
  get 'auth/:provider/callback', to: 'authentications#create'
  get 'auth/failure', to: 'authentications#failure'
  
  resources :authentications
  resources :users
  resources :groups
  resources :connections
  resources :saved_files
  resources :sessions, only: [:new, :create, :destroy]
  
  root 'static_pages#home'
  match '/help',          to: 'static_pages#help',          via: 'get'
  match '/about',         to: 'static_pages#about',         via: 'get'
  match '/contact',       to: 'static_pages#contact',       via: 'get'
  match '/privacyterms',  to: 'static_pages#privacyterms',  via: 'get'
  
  match '/signup',        to: 'users#new',                  via: 'get'
  match '/inbox',         to: 'users#inbox',                via: 'get',  as: :inbox
  
  match '/signin',        to: 'sessions#new',               via: 'get'
  match '/signout',       to: 'sessions#destroy',           via: 'delete'
  
  









end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  
  #Connections
  has_many :connections, :class_name => "Connection", :foreign_key => "user_id"
  has_many :contacts, through: :connections, :source => :contact
  
  #Connected by
  has_many :inverse_connections, :class_name => "Connection", :foreign_key => "contact_id"
  has_many :inverse_contacts, through: :inverse_connections, :source => :user
  
  #Group_connections
  has_many :group_connections, :foreign_key => "contact_id"
  has_many :groups, through: :group_connections
  
  #Owned groups
  has_many :owned_groups, :class_name => "Group", :foreign_key => "owner_id"
  
  #Method to find the given number of newest received files
  def find_newest_files(number_of_files)
    
    # Get the different connection_saved_files arrays from all the inverse connections and put them together in one array
    csfs = self.inverse_connections.map(&:connection_saved_files ).flatten
    
    # Sort the connectoin_saved_file array desc by the time the were updated
    csfs = csfs.sort_by{ |csf| csf.updated_at}.reverse
    
    # Return the first number of files from the list
    return csfs.take(number_of_files)
  end
  
  before_save {self.email = email.downcase}
  before_create :create_remember_token
  validates( :name,   presence: true, length: { maximum: 50 })
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates( :email,  presence: true, format: { with: VALID_EMAIL_REGEX}, uniqueness: {case_sensative: false})
  
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  #OmniAuth
  def from_omniauth(auth)
      self.name = auth.info.name
      self.email = auth.info.email
      tempPassword = SecureRandom.urlsafe_base64
      self.password = tempPassword
      self.password_confirmation = tempPassword
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  def email_taken?
    self.class.exists?(:email => email)
  end
  
  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #Redirect to user profile. First loading user and store it in @user variable to be used in UsersViews:show
  def show
    @user = User.find(params[:id])
  end
  
  #Redirect to a list of users: UserView:index
  def index
    @users = User.all
  end
  
  #Redirect to UsersViews:new where a user can create a new account
  def new
    @user = User.new
  end
  
  #Redirect to UserView:inbox where the file inbox of the user is showed
  def inbox
    @user = current_user
  end
  
  #gets form info from UsersView:new and handles it
  def create
    @user = User.new(user_params)    
    if @user.save
      sign_in @user, false
      flash[:success] = "Welcome to Zend!"
      redirect_to inbox_path
    else
      render 'new'
    end
  end
  
  private

    #method to set required parameters for creating account
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/inbox.html.erb
<% provide(:title, 'Inbox') %>

<p>Username: <%=h @user.name %></p>

<h2>Connections</h2>
<ul>
  <% for connection in @user.connections %>
    <li>
      <%=h connection.contact.name %>
      (<%= link_to "remove", connection, :method => :delete %>)
      (<%= link_to "Add file for this connection", new_saved_file_path(:connection_id => connection.id) %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Find Connections", new_connection_path %></p>

<h2>Groups you own</h2>
<p><%= link_to "Create group", new_group_path %></p>
<ul>
  <% for group in @user.owned_groups %>
    <li>
      <%=h group.name %>
      (
      <% group.group_connections.each do |connection|%>
      	<%= connection.contact.name%>  
      <% end %>
      )
    </li>
  <% end %>
</ul>

<h2>Groups you're part of</h2>
<ul>
  <% for group in @user.groups %>
    <li>
      <%=h group.name %>
      (
      <% group.group_connections.each do |connection|%>
      	<%= connection.contact.name%>  
      <% end %>
      )
    </li>
  <% end %>
</ul>

<h2>Connected by Users</h2>
<ul>
  <% for inverse_connection in @user.inverse_connections %>
    <li><%=h inverse_connection.user.name %></li>
  <% end %>
</ul>

<h2>Newest received files</h2>
<ul>
  <% @user.find_newest_files(5).each{ |csf| %>
  	<li>
  		<%= image_tag(csf.saved_file.name, size: "100x100", alt: csf.saved_file.name, title: csf.saved_file.name) %>
  		<%=h csf.saved_file.name %>
  		(<%=h csf.connection.user.name %>)
  	</li>
  <%}%>

</ul>

app/views/users/index.html.erb
<% provide(:title, 'User List') %>

<div id="users">
<% for user in @users %>
  <div class="user">
    <p>
      <strong><%=h user.name %></strong>
      <div class="clear"></div>
    </p>
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up test</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages' %>

    	<%= f.label :name %>
    	<%= f.text_field :name %>

    	<%= f.label :email %>
    	<%= f.text_field :email %>

    	<%= f.label :password %>
    	<%= f.password_field :password %>

    	<%= f.label :password_confirmation, "Confirmation" %>
    	<%= f.password_field :password_confirmation %>

    	<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>