config/routes.rb
Zend::Application.routes.draw do
  get 'auth/:provider/callback', to: 'authentications#create'
  get 'auth/failure', to: 'authentications#failure'
  
  resources :authentications
  resources :users
  resources :groups
  resources :connections
  resources :saved_files
  resources :sessions, only: [:new, :create, :destroy]
  
  root 'static_pages#home'
  match '/help',          to: 'static_pages#help',          via: 'get'
  match '/about',         to: 'static_pages#about',         via: 'get'
  match '/contact',       to: 'static_pages#contact',       via: 'get'
  match '/privacyterms',  to: 'static_pages#privacyterms',  via: 'get'
  
  match '/signup',        to: 'users#new',                  via: 'get'
  match '/inbox',         to: 'users#inbox',                via: 'get',  as: :inbox
  
  match '/signin',        to: 'sessions#new',               via: 'get'
  match '/signout',       to: 'sessions#destroy',           via: 'delete'
  
  









end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About Zend",   about_path %></li>
      <li><%= link_to "Privacy & Terms",   privacyterms_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-left">
        	
          <li class="logo"><%= link_to image_tag("text.png", size: "60x60", alt: "Zend logo"), root_path %></li>
          <!-- <li><%= link_to "Home", root_path %></li> -->
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li><%= link_to "Authentication", authentications_url %></li>
                <li><%= link_to "Inbox", inbox_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to image_tag("google-white-signin_long_base_44dp.png", size: '150x60', alt: "Sign in with Google+"), "/auth/google_oauth2", id: "sign_in_google" %></li>
            <li><%= link_to image_tag("facebook_signin.png", size: '150x60', alt: "Sign in with Facebook"), "/auth/facebook", id: "sign_in_facebook" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>